name: instax
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  intl: ^0.18.1

  # Firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.8.0

  #BLoC
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Custom Repository
  user_repository:
    path: packages/user_repository
  post_repository:
    path: packages/post_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
